all:
  children:
    ntpd_group:
      hosts:
        20.77.12.140:
          ansible_user: ops
          ansible_password: GP@D1ing!I0T
        20.77.11.241:
          ansible_user: ops
          ansible_password: GP@D1ing!I0T

