---
- name: Update the apt package cache
  apt:
    update_cache: yes
  when: ansible_os_family == "Debian"

- name: Install NTP package
  apt:
    name: ntp
    state: present
  when: ansible_os_family == "Debian"

- name: Ensure NTP service is started and enabled
  systemd:
    name: ntp
    state: started
    enabled: yes
  notify: Restart NTP service

