---
- name: Logrotate cron job every 10 minutes between 2h - 4h
  hosts: cron_group
  become: yes
  tasks:
    - name: Install logrotate
      apt:
        name: logrotate
        state: present
      when: ansible_os_family == "Debian"

    - name: Create logrotate configuration file
      copy:
        dest: /etc/logrotate.d/10min_logrotate
        content: |
          /var/log/auth.log {
              su root adm
              daily
              rotate 7
              compress
              missingok
              notifempty
          }

    - name: Configure cron job for logrotate
      cron:
         name: "Run logrotate every 10 minutes between 2h - 4h"
         minute: "*/10"
         hour: "2-4"
         job: "/usr/sbin/logrotate /etc/logrotate.d/10min_logrotate"
         user: root



